# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: 🇦🇹 M.Fox
email: markus.fox90@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Personal homepage of software developer and sim-racer Markus Fox.
twitter_username: username
github_username: markusfox
minimal_mistakes_skin: dark
search: true

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "Markus Fox"
  avatar : "/assets/images/photo.png"
  bio    : "AI/Software Engineer. Passionate Sim Racer (ACC). Crafting innovative solutions at the intersection of technology and passion."
  links:
  # ICONS at https://fontawesome.com/icons?d=gallery&p=9&m=free
    - label: "Klagenfurt, Austria"
      icon: "fas fa-fw fa-map-marker-alt"
      url: ""
    # - label: "Website"
    #   icon: "fas fa-fw fa-link"
    # - label: "Twitter"
    #   icon: "fab fa-fw fa-twitter-square"
    #   url: "https://twitter.com/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/MarkusFox"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/markusfox90/"
    - label: "GoogleScholar"
      icon: "fas fa-fw fa-graduation-cap"
      url: "https://scholar.google.at/citations?user=xNWo_VAAAAAJ&hl=de"
    # - label: "Medium"
    #   icon: "fab fa-fw fa-medium"
    #   url: "https://medium.com/@markus.fox90"
    - label: "TheSimGrid"
      icon: "fas fa-fw fa-flag-checkered"
      url: "https://www.thesimgrid.com/drivers/9578-markusfox"
    # - label: "Fuel Calculator"
    #   icon: "fas fa-fw fa-gas-pump"
    #   url: "/fuel-calculator/"
    # - label: "Instagram"
    #   icon: "fab fa-fw fa-instagram"
    #   url: "https://instagram.com/"

footer:
  links:
    - label: " "
      icon: "fab fa-fw fa-github"
      url: "https://github.com/MarkusFox"
    - label: " "
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/markusfox90/"
    - label: " "
      icon: "fas fa-fw fa-graduation-cap"
      url: "https://scholar.google.at/citations?user=xNWo_VAAAAAJ&hl=de"
    # - label: " "
    #   icon: "fab fa-fw fa-medium"
    #   url: "https://medium.com/@markus.fox90"
    - label: " "
      icon: "fas fa-fw fa-flag-checkered"
      url: "https://www.thesimgrid.com/drivers/9578-markusfox"
    # - label: " "
    #   icon: "fas fa-fw fa-gas-pump"
    #   url: "/fuel-calculator/"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      show_date: true
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

# disable RSS icon
atom_feed:
  hide: true
